### ISSUE TITLE
Market heads up

### ISSUE THREAD

**Issue by maddeningPup** [NoPawse/DNPCRAFT#2]
1: If you choose to do spawners i would suggest putting them at a relatively high price to avoid people buying an TON of them and making massive farms. sure we have mob stack but it could still cause issues

2: Observers cost less than Hoppers

3:  Missing Guardian Drops (Scales and Shards)

**Comment by maddeningPup** [comment]
also the dyes are all different prices. not sure if that is intentional or...?

**Comment by NoPawse** [comment]
I have just updated the shop! Thanks for letting us know, if you have any other suggestions please let me know!
